Repository NUM-Forschungsdatenplattform/num-portal-webapp, pull requests merged in 2024-09, with the labels that each got.

#644 uncomment attachments and add a label that shows the user to save pro…
  src/app/modules/projects/components/project-editor-general-info/project-editor-general-info.component.html
  src/app/shared/components/attachments-table/attachments-table.component.html
  src/assets/i18n/de.json
  src/assets/i18n/en.json
Labels: feature

#628 Use both archetype and template name for reference key
  src/app/shared/models/aqb/aqb-ui.model.ts
Labels: bug, improvement

#627 Use both composition and template name for reference key
  src/app/shared/models/aqb/aqb-ui.model.ts
Labels: bug, improvement

#632 Change approved user component to use full width
  src/app/modules/user-management/components/approved-users/approved-users.component.scss
Labels: improvement

#634 Use correct labels and i18n in where item component
  src/app/modules/aqls/components/aql-builder-where-item/aql-builder-where-item.component.html
  src/assets/i18n/de.json
  src/assets/i18n/en.json
Labels: improvement
